clear;
close all;
clc;

startup;

%% Configuration

cfg = mmw.config.defaultConfig();

array = mmw.geometry.makeArray( ...
    "golomb", ...
    cfg.array);

carrierHz = (60:0.4:64) * 1e9;
numCarriers = numel(carrierHz);

maxTargets = 2;


%% Build the problematic 60-degree scene

scene = mmw.geometry.makeScene( ...
    "two", ...
    cfg.scene, ...
    0.05);

scene.targets(1).scatterPhaseRad = 0;
scene.targets(2).scatterPhaseRad = deg2rad(60);


%% Generate observation

study = mmw.fusion.runCarrierSet( ...
    cfg, ...
    array, ...
    scene, ...
    carrierHz, ...
    "coherent-normalized");


%% Run current OMP

ompResult = ...
    mmw.reconstruction.ompMultiCarrier( ...
        cfg, ...
        array, ...
        study, ...
        maxTargets);


%% Current first detected position

pDetected = ompResult.positionsM(1,:);

fprintf('\n========================================\n');
fprintf('CURRENT OMP FIRST DETECTION\n');
fprintf('========================================\n');

fprintf( ...
    'Detected = (%.4f, %.4f, %.4f) m\n', ...
    pDetected(1), ...
    pDetected(2), ...
    pDetected(3));


%% True Target-1 position
%
% Truth is used ONLY for this diagnostic experiment.

pTrue = scene.targets(1).positionM;

fprintf( ...
    'Truth    = (%.4f, %.4f, %.4f) m\n', ...
    pTrue(1), ...
    pTrue(2), ...
    pTrue(3));


%% ------------------------------------------------------------
% Reconstruct the residual AFTER OMP iteration 1
%
% r1 = y - alpha1_hat * s1
% ------------------------------------------------------------

alphaIteration1 = ...
    ompResult.alphaHistory{1};

alpha1 = ...
    alphaIteration1(1);

residualIF1 = ...
    cell(1, numCarriers);


for k = 1:numCarriers

    yObserved = ...
        study.carrierResults{k}.ifData;

    sDetected = ...
        ompResult.templateIF{1,k};

    residualIF1{k} = ...
        yObserved - ...
        alpha1 * sDetected;

end


%% ------------------------------------------------------------
% Compare STRICT OMP scores around the first BP peak
%
% We compare:
%
% 1. BP-selected point:
%       (2.9750, 3.0025)
%
% 2. True point:
%       (2.9750, 3.0000)
%
% IMPORTANT:
%
% For FIRST-target selection, the strict score should be
% evaluated against the ORIGINAL observation, not residualIF1.
% ------------------------------------------------------------

originalIF = ...
    cell(1, numCarriers);

for k = 1:numCarriers

    originalIF{k} = ...
        study.carrierResults{k}.ifData;

end


scoreDetected = ...
    calculateStrictScore( ...
        cfg, ...
        array, ...
        carrierHz, ...
        originalIF, ...
        pDetected);


scoreTrue = ...
    calculateStrictScore( ...
        cfg, ...
        array, ...
        carrierHz, ...
        originalIF, ...
        pTrue);


fprintf('\n========================================\n');
fprintf('STRICT OMP SCORE COMPARISON\n');
fprintf('========================================\n');

fprintf( ...
    'BP-selected point : (%.4f, %.4f)\n', ...
    pDetected(1), ...
    pDetected(2));

fprintf( ...
    'Strict score      : %.12e\n', ...
    scoreDetected);


fprintf('\n');

fprintf( ...
    'True point        : (%.4f, %.4f)\n', ...
    pTrue(1), ...
    pTrue(2));

fprintf( ...
    'Strict score      : %.12e\n', ...
    scoreTrue);


fprintf('\n');

fprintf( ...
    'True / detected score ratio = %.9f\n', ...
    scoreTrue / scoreDetected);


if scoreTrue > scoreDetected

    fprintf('\nRESULT:\n');
    fprintf('Strict OMP prefers the TRUE position.\n');

else

    fprintf('\nRESULT:\n');
    fprintf('Strict OMP still prefers the BP-selected position.\n');

end


%% ------------------------------------------------------------
% Local 5 x 5 strict-score search around BP result
% ------------------------------------------------------------

gridStepM = cfg.imaging.gridStepM;

offsetIndex = -2:2;

scoreMap = zeros( ...
    numel(offsetIndex), ...
    numel(offsetIndex));


bestScore = -Inf;
bestPositionM = pDetected;


for iy = 1:numel(offsetIndex)

    for ix = 1:numel(offsetIndex)

        candidatePositionM = [ ...
            pDetected(1) + ...
                offsetIndex(ix) * gridStepM, ...
            pDetected(2) + ...
                offsetIndex(iy) * gridStepM, ...
            cfg.imaging.zM];


        score = ...
            calculateStrictScore( ...
                cfg, ...
                array, ...
                carrierHz, ...
                originalIF, ...
                candidatePositionM);


        scoreMap(iy,ix) = score;


        if score > bestScore

            bestScore = score;
            bestPositionM = candidatePositionM;

        end

    end

end


fprintf('\n========================================\n');
fprintf('LOCAL STRICT OMP SEARCH\n');
fprintf('========================================\n');

fprintf( ...
    'BP position     : (%.4f, %.4f) m\n', ...
    pDetected(1), ...
    pDetected(2));

fprintf( ...
    'Refined position: (%.4f, %.4f) m\n', ...
    bestPositionM(1), ...
    bestPositionM(2));

fprintf( ...
    'Truth position  : (%.4f, %.4f) m\n', ...
    pTrue(1), ...
    pTrue(2));

fprintf( ...
    'Best score      : %.12e\n', ...
    bestScore);


%% Plot local score map

xCandidate = ...
    pDetected(1) + ...
    offsetIndex * gridStepM;

yCandidate = ...
    pDetected(2) + ...
    offsetIndex * gridStepM;


figure( ...
    'Name', ...
    'Local strict OMP score');


imagesc( ...
    xCandidate, ...
    yCandidate, ...
    scoreMap);

axis xy equal tight;

xlabel('x / m');
ylabel('y / m');

title('Strict OMP score around BP peak');

colorbar;

hold on;

plot( ...
    pDetected(1), ...
    pDetected(2), ...
    'kx', ...
    'LineWidth', ...
    2, ...
    'MarkerSize', ...
    12);

plot( ...
    pTrue(1), ...
    pTrue(2), ...
    'ro', ...
    'LineWidth', ...
    2, ...
    'MarkerSize', ...
    10);

plot( ...
    bestPositionM(1), ...
    bestPositionM(2), ...
    'g+', ...
    'LineWidth', ...
    2, ...
    'MarkerSize', ...
    12);

legend( ...
    'BP detection', ...
    'Truth', ...
    'Strict-score maximum');


%% ============================================================
% Local function
% ============================================================

function score = calculateStrictScore( ...
    cfg, array, carrierHz, residualIF, positionM)

numCarriers = numel(carrierHz);


%% Unit target at candidate position

target = struct();

target.name = "Candidate";
target.positionM = positionM;
target.velocityMps = cfg.scene.defaultVelocityMps;
target.rcsM2 = 1.0;
target.scatterPhaseRad = 0.0;


scene = struct();

scene.type = "single";
scene.separationM = NaN;
scene.targets = target;


%% Strict multi-carrier correlation

numerator = 0;
denominator = 0;


templateCfg = cfg;
templateCfg.simulation.noiseStd = 0;


for k = 1:numCarriers

    cfgK = templateCfg;
    cfgK.waveform.fcHz = carrierHz(k);


    [s, ~] = ...
        mmw.signal.simulateIF( ...
            cfgK, ...
            array, ...
            scene);


    r = residualIF{k};


    numerator = ...
        numerator + ...
        sum( ...
            conj(s(:)) .* ...
            r(:));


    denominator = ...
        denominator + ...
        sum(abs(s(:)).^2);

end


score = ...
    abs(numerator) / ...
    sqrt(max(denominator, eps));

end