clear;
close all;
clc;

startup;

%% Configuration

cfg = mmw.config.defaultConfig();

array = mmw.geometry.makeArray( ...
    "golomb", ...
    cfg.array);

carrierHz = (60:0.4:64) * 1e9;

numCarriers = numel(carrierHz);


%% Build two-target scene

sceneTwo = mmw.geometry.makeScene( ...
    "two", ...
    cfg.scene, ...
    0.05);


%% Run original two-target simulation

fprintf('\n========================================\n');
fprintf('TWO-TARGET SCENE\n');
fprintf('========================================\n');

twoResult = mmw.fusion.runCarrierSet( ...
    cfg, ...
    array, ...
    sceneTwo, ...
    carrierHz, ...
    "coherent-normalized");


%% Detect strongest target from fused image

P = twoResult.fusedImage.coherentPower;

[~, linearIndex] = max(P(:));

[iy, ix] = ...
    ind2sub(size(P), linearIndex);

x = twoResult.fusedImage.xGridM;
y = twoResult.fusedImage.yGridM;

detectedPositionM = [ ...
    x(ix), ...
    y(iy), ...
    cfg.imaging.zM];


fprintf('\n========================================\n');
fprintf('STRONGEST TARGET DETECTION\n');
fprintf('========================================\n');

fprintf( ...
    'Detected position : (%.4f, %.4f, %.4f) m\n', ...
    detectedPositionM(1), ...
    detectedPositionM(2), ...
    detectedPositionM(3));


%% Build unit-reflectivity template target

templateTarget.name = ...
    "DetectedTemplate";

templateTarget.positionM = ...
    detectedPositionM;

templateTarget.velocityMps = ...
    cfg.scene.defaultVelocityMps;

templateTarget.rcsM2 = 1.0;

templateTarget.scatterPhaseRad = 0.0;

templateScene.type = "single";
templateScene.separationM = NaN;
templateScene.targets = templateTarget;


%% Generate unit-target IF templates

templateIF = cell(1, numCarriers);

numerator = 0;
denominator = 0;

for k = 1:numCarriers

    cfgK = cfg;
    cfgK.waveform.fcHz = carrierHz(k);

    [s, ~] = ...
        mmw.signal.simulateIF( ...
            cfgK, ...
            array, ...
            templateScene);

    templateIF{k} = s;

    yObserved = ...
        twoResult.carrierResults{k}.ifData;

    numerator = ...
        numerator + ...
        sum(conj(s(:)) .* yObserved(:));

    denominator = ...
        denominator + ...
        sum(abs(s(:)).^2);

end


%% Estimate complex scattering coefficient

alphaHat = ...
    numerator / ...
    max(denominator, eps);


fprintf('\n========================================\n');
fprintf('SCATTERING COEFFICIENT ESTIMATION\n');
fprintf('========================================\n');

fprintf( ...
    'Estimated amplitude : %.6f\n', ...
    abs(alphaHat));

fprintf( ...
    'Estimated phase     : %.3f deg\n', ...
    rad2deg(angle(alphaHat)));

fprintf( ...
    'Estimated alpha     : %.6f %+.6fj\n', ...
    real(alphaHat), ...
    imag(alphaHat));


%% Subtract reconstructed Target 1

residualComplexStack = [];

for k = 1:numCarriers

    cfgK = cfg;
    cfgK.waveform.fcHz = carrierHz(k);

    yObserved = ...
        twoResult.carrierResults{k}.ifData;

    s = ...
        templateIF{k};

    reconstructedIF = ...
        alphaHat * s;

    residualIF = ...
        yObserved - reconstructedIF;


    %% Process residual

    residualRD = ...
        mmw.processing.rangeDoppler( ...
            cfgK, ...
            residualIF);

    residualImage = ...
        mmw.imaging.coherentImage( ...
            cfgK, ...
            array, ...
            residualRD);


    %% Allocate stack

    if isempty(residualComplexStack)

        [numY, numX] = ...
            size(residualImage.coherentComplex);

        residualComplexStack = ...
            complex(zeros( ...
                numY, ...
                numX, ...
                numCarriers));

    end


    residualComplexStack(:,:,k) = ...
        residualImage.coherentComplex;

end


%% Multi-frequency fusion of CLEAN residual

[cleanPower, ...
 cleanComplex, ...
 cleanNormalizedStack] = ...
    mmw.fusion.fuseComplexImages( ...
        residualComplexStack, ...
        "normalized");


%% Build residual image

cleanImage = ...
    twoResult.carrierResults{1}.image;

cleanImage.coherentComplex = ...
    cleanComplex;

cleanImage.coherentPower = ...
    cleanPower;

cleanImage.nodeComplex = [];
cleanImage.nodePower = [];
cleanImage.noncoherentPower = [];

cleanImage.method = ...
    "detected CLEAN residual";


%% Detect strongest residual target

Pclean = cleanImage.coherentPower;

[~, residualLinearIndex] = ...
    max(Pclean(:));

[iyResidual, ixResidual] = ...
    ind2sub( ...
        size(Pclean), ...
        residualLinearIndex);

residualDetectedPositionM = [ ...
    x(ixResidual), ...
    y(iyResidual), ...
    cfg.imaging.zM];


fprintf('\n========================================\n');
fprintf('RESIDUAL TARGET DETECTION\n');
fprintf('========================================\n');

fprintf( ...
    'Residual strongest position : (%.4f, %.4f, %.4f) m\n', ...
    residualDetectedPositionM(1), ...
    residualDetectedPositionM(2), ...
    residualDetectedPositionM(3));


%% Ground-truth Target 2 scene
%
% Used ONLY for evaluation.
% It does not participate in CLEAN.

scene2 = sceneTwo;
scene2.type = "single";
scene2.targets = sceneTwo.targets(2);


%% Evaluate residual against Target 2

cleanMetrics = ...
    mmw.metrics.evaluateImage( ...
        cfg, ...
        scene2, ...
        cleanImage);


fprintf('\n========================================\n');
fprintf('DETECTED CLEAN RESULT\n');
fprintf('========================================\n');

fprintf( ...
    'Localization error : %.2f mm\n', ...
    1000 * cleanMetrics.localizationErrorM);

fprintf( ...
    'PSLR               : %.2f dB\n', ...
    cleanMetrics.pslrDb);

fprintf( ...
    'ISLR               : %.2f dB\n', ...
    cleanMetrics.islrDb);


%% Generate Target-2-only reference
%
% Evaluation only.

target2Result = ...
    mmw.fusion.runCarrierSet( ...
        cfg, ...
        array, ...
        scene2, ...
        carrierHz, ...
        "coherent-normalized");


%% Compare CLEAN result with ideal Target-2-only result

cleanVsTruthError = ...
    norm( ...
        cleanComplex(:) - ...
        target2Result.fusedImage.coherentComplex(:)) / ...
    max( ...
        norm( ...
            target2Result.fusedImage.coherentComplex(:)), ...
        eps);


fprintf( ...
    'Fused-image relative error : %.3e\n', ...
    cleanVsTruthError);


%% Reference metrics

referenceMetrics = ...
    target2Result.metrics;

fprintf('\n========================================\n');
fprintf('TARGET 2 REFERENCE\n');
fprintf('========================================\n');

fprintf( ...
    'Localization error : %.2f mm\n', ...
    1000 * referenceMetrics.localizationErrorM);

fprintf( ...
    'PSLR               : %.2f dB\n', ...
    referenceMetrics.pslrDb);

fprintf( ...
    'ISLR               : %.2f dB\n', ...
    referenceMetrics.islrDb);


%% Plot comparison

Ptwo = ...
    twoResult.fusedImage.coherentPower;

Pclean = ...
    cleanImage.coherentPower;

Ptarget2 = ...
    target2Result.fusedImage.coherentPower;

Ptwo = ...
    Ptwo / max(Ptwo(:));

Pclean = ...
    Pclean / max(Pclean(:));

Ptarget2 = ...
    Ptarget2 / max(Ptarget2(:));

dynamicRangeDb = ...
    cfg.plot.dynamicRangeDb;


figure( ...
    'Name', ...
    'Detected CLEAN validation', ...
    'Position', ...
    [100 150 1500 500]);

tiledlayout( ...
    1, ...
    3, ...
    'TileSpacing', ...
    'compact', ...
    'Padding', ...
    'compact');


%% Original

nexttile;

imagesc( ...
    x, ...
    y, ...
    10*log10(Ptwo + eps));

axis xy equal tight;

clim([-dynamicRangeDb 0]);

xlabel('x / m');
ylabel('y / m');

title('Original two-target image');


%% CLEAN residual

nexttile;

imagesc( ...
    x, ...
    y, ...
    10*log10(Pclean + eps));

axis xy equal tight;

clim([-dynamicRangeDb 0]);

xlabel('x / m');
ylabel('y / m');

title('Detected CLEAN residual');


%% Target 2 reference

nexttile;

imagesc( ...
    x, ...
    y, ...
    10*log10(Ptarget2 + eps));

axis xy equal tight;

clim([-dynamicRangeDb 0]);

xlabel('x / m');
ylabel('y / m');

title('Target 2 only');

colorbar;


%% Difference image

figure( ...
    'Name', ...
    'Detected CLEAN image difference');

imagesc( ...
    x, ...
    y, ...
    abs(Pclean - Ptarget2));

axis xy equal tight;

xlabel('x / m');
ylabel('y / m');

title( ...
    'Absolute power difference: detected CLEAN vs Target 2');

colorbar;


%% Final summary

fprintf('\n========================================\n');
fprintf('DETECTED CLEAN SUMMARY\n');
fprintf('========================================\n');

fprintf( ...
    'First detected position : (%.4f, %.4f) m\n', ...
    detectedPositionM(1), ...
    detectedPositionM(2));

fprintf( ...
    'Residual target position: (%.4f, %.4f) m\n', ...
    residualDetectedPositionM(1), ...
    residualDetectedPositionM(2));

fprintf( ...
    'Estimated alpha amplitude: %.6f\n', ...
    abs(alphaHat));

fprintf( ...
    'Estimated alpha phase    : %.3f deg\n', ...
    rad2deg(angle(alphaHat)));

fprintf( ...
    'CLEAN localization       : %.2f mm\n', ...
    1000 * cleanMetrics.localizationErrorM);

fprintf( ...
    'Reference localization   : %.2f mm\n', ...
    1000 * referenceMetrics.localizationErrorM);

fprintf( ...
    'CLEAN PSLR               : %.2f dB\n', ...
    cleanMetrics.pslrDb);

fprintf( ...
    'Reference PSLR           : %.2f dB\n', ...
    referenceMetrics.pslrDb);

fprintf( ...
    'CLEAN ISLR               : %.2f dB\n', ...
    cleanMetrics.islrDb);

fprintf( ...
    'Reference ISLR           : %.2f dB\n', ...
    referenceMetrics.islrDb);

fprintf( ...
    'Fused-image error        : %.3e\n', ...
    cleanVsTruthError);