clear;
close all;
clc;

startup;

%% Configuration

cfg = mmw.config.defaultConfig();

array = mmw.geometry.makeArray( ...
    "golomb", ...
    cfg.array);

carrierHz = (60:0.4:64) * 1e9;


%% Build two-target scene

sceneTwo = mmw.geometry.makeScene( ...
    "two", ...
    cfg.scene, ...
    0.05);


%% Split into two single-target scenes

scene1 = sceneTwo;
scene1.type = "single";
scene1.targets = sceneTwo.targets(1);

scene2 = sceneTwo;
scene2.type = "single";
scene2.targets = sceneTwo.targets(2);


%% Run three reference simulations

fprintf('\n========================================\n');
fprintf('TWO-TARGET SCENE\n');
fprintf('========================================\n');

twoResult = mmw.fusion.runCarrierSet( ...
    cfg, ...
    array, ...
    sceneTwo, ...
    carrierHz, ...
    "coherent-normalized");


fprintf('\n========================================\n');
fprintf('TARGET 1 ONLY\n');
fprintf('========================================\n');

target1Result = mmw.fusion.runCarrierSet( ...
    cfg, ...
    array, ...
    scene1, ...
    carrierHz, ...
    "coherent-normalized");


fprintf('\n========================================\n');
fprintf('TARGET 2 ONLY\n');
fprintf('========================================\n');

target2Result = mmw.fusion.runCarrierSet( ...
    cfg, ...
    array, ...
    scene2, ...
    carrierHz, ...
    "coherent-normalized");


%% Oracle CLEAN in IF domain

numCarriers = numel(carrierHz);

residualComplexStack = [];

ifError = zeros(numCarriers, 1);
rdError = zeros(numCarriers, 1);
imageError = zeros(numCarriers, 1);


for k = 1:numCarriers

    cfgK = cfg;
    cfgK.waveform.fcHz = carrierHz(k);

    rTwo = twoResult.carrierResults{k};
    r1   = target1Result.carrierResults{k};
    r2   = target2Result.carrierResults{k};


    %% Remove Target 1 in complex IF domain

    residualIF = ...
        rTwo.ifData - r1.ifData;


    %% Re-run Range-Doppler processing

    residualRD = ...
        mmw.processing.rangeDoppler( ...
            cfgK, ...
            residualIF);


    %% Re-run coherent imaging

    residualImage = ...
        mmw.imaging.coherentImage( ...
            cfgK, ...
            array, ...
            residualRD);


    %% Allocate multi-carrier complex image stack

    if isempty(residualComplexStack)

        [numY, numX] = ...
            size(residualImage.coherentComplex);

        residualComplexStack = ...
            complex(zeros( ...
                numY, ...
                numX, ...
                numCarriers));

    end


    residualComplexStack(:,:,k) = ...
        residualImage.coherentComplex;


    %% Compare residual with true Target-2-only result

    ifError(k) = ...
        norm( ...
            residualIF(:) - ...
            r2.ifData(:)) / ...
        max( ...
            norm(r2.ifData(:)), ...
            eps);


    rdError(k) = ...
        norm( ...
            residualRD.iq(:) - ...
            r2.rd.iq(:)) / ...
        max( ...
            norm(r2.rd.iq(:)), ...
            eps);


    imageError(k) = ...
        norm( ...
            residualImage.coherentComplex(:) - ...
            r2.image.coherentComplex(:)) / ...
        max( ...
            norm(r2.image.coherentComplex(:)), ...
            eps);

end


%% Linear reconstruction check

fprintf('\n========================================\n');
fprintf('ORACLE CLEAN LINEARITY CHECK\n');
fprintf('========================================\n');

fprintf( ...
    'Maximum IF relative error    : %.3e\n', ...
    max(ifError));

fprintf( ...
    'Maximum RD relative error    : %.3e\n', ...
    max(rdError));

fprintf( ...
    'Maximum image relative error : %.3e\n', ...
    max(imageError));


%% Multi-frequency coherent fusion of residual

[cleanPower, ...
 cleanComplex, ...
 cleanNormalizedStack] = ...
    mmw.fusion.fuseComplexImages( ...
        residualComplexStack, ...
        "normalized");


%% Build CLEAN image structure

cleanImage = ...
    target2Result.carrierResults{1}.image;

cleanImage.coherentComplex = ...
    cleanComplex;

cleanImage.coherentPower = ...
    cleanPower;

cleanImage.nodeComplex = [];
cleanImage.nodePower = [];
cleanImage.noncoherentPower = [];

cleanImage.method = ...
    "oracle CLEAN + multi-frequency coherent fusion";


%% Evaluate CLEAN result as a single-target scene

cleanMetrics = ...
    mmw.metrics.evaluateImage( ...
        cfg, ...
        scene2, ...
        cleanImage);


fprintf('\n========================================\n');
fprintf('ORACLE CLEAN RESULT\n');
fprintf('========================================\n');

fprintf( ...
    'Localization error : %.2f mm\n', ...
    1000 * cleanMetrics.localizationErrorM);

fprintf( ...
    'PSLR               : %.2f dB\n', ...
    cleanMetrics.pslrDb);

fprintf( ...
    'ISLR               : %.2f dB\n', ...
    cleanMetrics.islrDb);


%% Compare fused CLEAN result with true Target-2-only result

cleanVsTruthError = ...
    norm( ...
        cleanComplex(:) - ...
        target2Result.fusedImage.coherentComplex(:)) / ...
    max( ...
        norm( ...
            target2Result.fusedImage.coherentComplex(:)), ...
        eps);


fprintf( ...
    'Fused-image relative error : %.3e\n', ...
    cleanVsTruthError);


%% Compare Target-2-only reference metrics

referenceMetrics = ...
    target2Result.metrics;

fprintf('\n========================================\n');
fprintf('TARGET 2 ONLY REFERENCE\n');
fprintf('========================================\n');

fprintf( ...
    'Localization error : %.2f mm\n', ...
    1000 * referenceMetrics.localizationErrorM);

fprintf( ...
    'PSLR               : %.2f dB\n', ...
    referenceMetrics.pslrDb);

fprintf( ...
    'ISLR               : %.2f dB\n', ...
    referenceMetrics.islrDb);


%% Print each-carrier reconstruction error

fprintf('\n========================================\n');
fprintf('PER-CARRIER ERROR\n');
fprintf('========================================\n');

for k = 1:numCarriers

    fprintf( ...
        '%.1f GHz | IF %.3e | RD %.3e | Image %.3e\n', ...
        carrierHz(k) / 1e9, ...
        ifError(k), ...
        rdError(k), ...
        imageError(k));

end


%% Plot comparison

x = cleanImage.xGridM;
y = cleanImage.yGridM;

Ptwo = ...
    twoResult.fusedImage.coherentPower;

Pclean = ...
    cleanImage.coherentPower;

Ptarget2 = ...
    target2Result.fusedImage.coherentPower;


%% Normalize independently for display

Ptwo = ...
    Ptwo / max(Ptwo(:));

Pclean = ...
    Pclean / max(Pclean(:));

Ptarget2 = ...
    Ptarget2 / max(Ptarget2(:));


dynamicRangeDb = ...
    cfg.plot.dynamicRangeDb;


figure( ...
    'Name', ...
    'Oracle CLEAN validation', ...
    'Position', ...
    [100 150 1500 500]);


tiledlayout( ...
    1, ...
    3, ...
    'TileSpacing', ...
    'compact', ...
    'Padding', ...
    'compact');


%% Original two-target image

nexttile;

imagesc( ...
    x, ...
    y, ...
    10*log10(Ptwo + eps));

axis xy equal tight;

clim( ...
    [-dynamicRangeDb 0]);

xlabel('x / m');
ylabel('y / m');

title( ...
    'Original two-target image');


%% Oracle CLEAN result

nexttile;

imagesc( ...
    x, ...
    y, ...
    10*log10(Pclean + eps));

axis xy equal tight;

clim( ...
    [-dynamicRangeDb 0]);

xlabel('x / m');
ylabel('y / m');

title( ...
    'After removing Target 1');


%% True Target-2-only result

nexttile;

imagesc( ...
    x, ...
    y, ...
    10*log10(Ptarget2 + eps));

axis xy equal tight;

clim( ...
    [-dynamicRangeDb 0]);

xlabel('x / m');
ylabel('y / m');

title( ...
    'Target 2 only');

colorbar;


%% Plot CLEAN / truth image difference

Pdifference = ...
    abs(Pclean - Ptarget2);

figure( ...
    'Name', ...
    'Oracle CLEAN image difference');

imagesc( ...
    x, ...
    y, ...
    Pdifference);

axis xy equal tight;

xlabel('x / m');
ylabel('y / m');

title( ...
    'Absolute power difference: CLEAN vs Target 2 only');

colorbar;


%% Summary

fprintf('\n========================================\n');
fprintf('ORACLE CLEAN SUMMARY\n');
fprintf('========================================\n');

fprintf( ...
    'IF maximum error       : %.3e\n', ...
    max(ifError));

fprintf( ...
    'RD maximum error       : %.3e\n', ...
    max(rdError));

fprintf( ...
    'Image maximum error    : %.3e\n', ...
    max(imageError));

fprintf( ...
    'Fused-image error      : %.3e\n', ...
    cleanVsTruthError);

fprintf('\n');

fprintf( ...
    'CLEAN localization     : %.2f mm\n', ...
    1000 * cleanMetrics.localizationErrorM);

fprintf( ...
    'Reference localization : %.2f mm\n', ...
    1000 * referenceMetrics.localizationErrorM);

fprintf( ...
    'CLEAN PSLR             : %.2f dB\n', ...
    cleanMetrics.pslrDb);

fprintf( ...
    'Reference PSLR         : %.2f dB\n', ...
    referenceMetrics.pslrDb);

fprintf( ...
    'CLEAN ISLR             : %.2f dB\n', ...
    cleanMetrics.islrDb);

fprintf( ...
    'Reference ISLR         : %.2f dB\n', ...
    referenceMetrics.islrDb);