clear;
close all;
clc;

startup;


%% ============================================================
% Configuration
% =============================================================

cfg = ...
    mmw.config.defaultConfig();

array = ...
    mmw.geometry.makeArray( ...
        "golomb", ...
        cfg.array);

carrierHz = ...
    (60:0.4:64) * 1e9;

numTargets = 4;


%% ============================================================
% Four-target geometry
%
% All positions are on the 2.5 mm imaging grid.
% Pairwise distances are all different.
% Minimum distance = 5 cm.
% =============================================================

positionsM = [
    2.9300, 2.9800, 1.2000
    2.9800, 2.9800, 1.2000
    3.0400, 3.0100, 1.2000
    3.1000, 2.9500, 1.2000
];


%% ============================================================
% Check pairwise distances
% =============================================================

distanceMatrixM = ...
    zeros(numTargets);

pairDistancesM = [];


fprintf('\n========================================\n');
fprintf('PAIRWISE TARGET DISTANCES\n');
fprintf('========================================\n');


for i = 1:numTargets

    for j = i+1:numTargets

        distanceM = ...
            norm( ...
                positionsM(i,1:2) - ...
                positionsM(j,1:2));

        distanceMatrixM(i,j) = ...
            distanceM;

        distanceMatrixM(j,i) = ...
            distanceM;

        pairDistancesM(end+1) = ...
            distanceM; %#ok<SAGROW>

        fprintf( ...
            'T%d - T%d : %.3f cm\n', ...
            i, ...
            j, ...
            100 * distanceM);

    end

end


minDistanceM = ...
    min(pairDistancesM);


fprintf('\nMinimum distance : %.3f cm\n', ...
    100 * minDistanceM);


if minDistanceM < 0.05 - 1e-12

    error( ...
        'Minimum target spacing is below 5 cm.');

end


%% ============================================================
% Build custom four-target scene
% =============================================================

sceneFour = ...
    mmw.geometry.makeCustomScene( ...
        positionsM, ...
        cfg.scene);


%% Keep first experiment simple:
% equal RCS and zero scattering phase

for m = 1:numTargets

    sceneFour.targets(m).rcsM2 = ...
        1.0;

    sceneFour.targets(m).scatterPhaseRad = ...
        0.0;

end


%% ============================================================
% Generate four-target multi-carrier observation
% =============================================================

fprintf('\n========================================\n');
fprintf('GENERATING FOUR-TARGET OBSERVATION\n');
fprintf('========================================\n');


fourResult = ...
    mmw.fusion.runCarrierSet( ...
        cfg, ...
        array, ...
        sceneFour, ...
        carrierHz, ...
        "coherent-normalized");


%% ============================================================
% Run four-target OMP
% =============================================================

fprintf('\n========================================\n');
fprintf('RUNNING FOUR-TARGET OMP\n');
fprintf('========================================\n');


ompResult = ...
    mmw.reconstruction.ompMultiCarrier( ...
        cfg, ...
        array, ...
        fourResult, ...
        numTargets);


%% ============================================================
% Raw detection order
% =============================================================

fprintf('\n========================================\n');
fprintf('OMP DETECTION ORDER\n');
fprintf('========================================\n');


for m = 1:numTargets

    fprintf( ...
        'Iteration %d : (%.4f, %.4f, %.4f) m', ...
        m, ...
        ompResult.positionsM(m,1), ...
        ompResult.positionsM(m,2), ...
        ompResult.positionsM(m,3));

    fprintf( ...
        ' |alpha| = %.9f, phase = %.6f deg\n', ...
        abs(ompResult.alpha(m)), ...
        rad2deg(angle(ompResult.alpha(m))));

end


%% ============================================================
% Match OMP detections to truth
%
% OMP detection order does not have to equal T1,T2,T3,T4.
% For four targets there are only 4! = 24 assignments, so
% exhaustive matching is simple and unambiguous.
% =============================================================

truthXY = ...
    positionsM(:,1:2);

detectedXY = ...
    ompResult.positionsM(:,1:2);


[matchedDetectedXY, ...
 matchedAlpha, ...
 assignment] = ...
    matchDetectionsToTruth( ...
        truthXY, ...
        detectedXY, ...
        ompResult.alpha);


%% ============================================================
% Truth complex coefficients
% =============================================================

truthAlpha = ...
    complex(zeros(numTargets,1));


for m = 1:numTargets

    truthAlpha(m) = ...
        sqrt(sceneFour.targets(m).rcsM2) * ...
        exp( ...
            1j * ...
            sceneFour.targets(m).scatterPhaseRad);

end


%% ============================================================
% Errors
% =============================================================

positionErrorM = ...
    vecnorm( ...
        matchedDetectedXY - ...
        truthXY, ...
        2, ...
        2);


alphaError = ...
    matchedAlpha - ...
    truthAlpha;


supportPass = ...
    all( ...
        positionErrorM <= ...
        cfg.metrics.targetMatchRadiusM);

maxPositionErrorMm = ...
    1000 * max(positionErrorM);

rmsePositionMm = ...
    1000 * sqrt(mean(positionErrorM.^2));


%% ============================================================
% Print final comparison
% =============================================================

fprintf('\n========================================\n');
fprintf('FOUR-TARGET RESULT\n');
fprintf('========================================\n');


for m = 1:numTargets

    fprintf('\nTarget %d\n', m);

    fprintf( ...
        'Truth position     : (%.4f, %.4f) m\n', ...
        truthXY(m,1), ...
        truthXY(m,2));

    fprintf( ...
        'Detected position  : (%.4f, %.4f) m\n', ...
        matchedDetectedXY(m,1), ...
        matchedDetectedXY(m,2));

    fprintf( ...
        'Position error     : %.6f mm\n', ...
        1000 * positionErrorM(m));

    fprintf( ...
        'True alpha         : %.9f %+.9fj\n', ...
        real(truthAlpha(m)), ...
        imag(truthAlpha(m)));

    fprintf( ...
        'Estimated alpha    : %.9f %+.9fj\n', ...
        real(matchedAlpha(m)), ...
        imag(matchedAlpha(m)));

    fprintf( ...
        'Alpha error        : %.3e\n', ...
        abs(alphaError(m)));

end


fprintf('\n');

fprintf( ...
    'Support pass             : %d\n', ...
    supportPass);

fprintf( ...
    'Maximum position error   : %.3f mm\n', ...
    maxPositionErrorMm);

fprintf( ...
    'Position RMSE            : %.3f mm\n', ...
    rmsePositionMm);

fprintf( ...
    'Final residual error     : %.3e\n', ...
    ompResult.finalResidualRelativeError);

fprintf( ...
    'Maximum coherence        : %.6f\n', ...
    ompResult.maximumTemplateCoherence);

fprintf( ...
    'Gram condition number    : %.6f\n', ...
    ompResult.gramConditionNumber);

fprintf( ...
    'Final residual error     : %.3e\n', ...
    ompResult.finalResidualRelativeError);

fprintf( ...
    'Maximum coherence        : %.6f\n', ...
    ompResult.maximumTemplateCoherence);

fprintf( ...
    'Gram condition number    : %.6f\n', ...
    ompResult.gramConditionNumber);


%% ============================================================
% Display coherence matrix
% =============================================================

fprintf('\nTemplate coherence matrix:\n');

disp( ...
    ompResult.templateCoherenceMatrix);


%% ============================================================
% Plot 1: original four-target multi-carrier image
% =============================================================

P = ...
    fourResult.fusedImage.coherentPower;

P = ...
    P / max(P(:));


x = ...
    fourResult.fusedImage.xGridM;

y = ...
    fourResult.fusedImage.yGridM;


figure( ...
    'Name', ...
    'Four-target multi-carrier image', ...
    'Color', ...
    'w');


imagesc( ...
    x, ...
    y, ...
    10*log10(P + eps));

axis xy equal tight;

clim([-40 0]);

colormap turbo;

colorbar;

xlabel('x / m');
ylabel('y / m');

title('Original four-target multi-carrier image');


hold on;


plot( ...
    truthXY(:,1), ...
    truthXY(:,2), ...
    'wo', ...
    'MarkerSize', ...
    8, ...
    'LineWidth', ...
    1.5);


plot( ...
    detectedXY(:,1), ...
    detectedXY(:,2), ...
    'wx', ...
    'MarkerSize', ...
    8, ...
    'LineWidth', ...
    1.5);


legend( ...
    {'Truth', 'OMP estimate'}, ...
    'Location', ...
    'northeast');


hold off;


%% ============================================================
% Plot 2: OMP support only
% =============================================================

figure( ...
    'Name', ...
    'Four-target OMP support', ...
    'Color', ...
    'w');


plot( ...
    truthXY(:,1), ...
    truthXY(:,2), ...
    'ko', ...
    'MarkerSize', ...
    7, ...
    'LineWidth', ...
    1.5);

hold on;


plot( ...
    detectedXY(:,1), ...
    detectedXY(:,2), ...
    'rx', ...
    'MarkerSize', ...
    8, ...
    'LineWidth', ...
    1.5);


axis equal;

marginM = 0.03;

xlim([ ...
    min(truthXY(:,1)) - marginM, ...
    max(truthXY(:,1)) + marginM]);

ylim([ ...
    min(truthXY(:,2)) - marginM, ...
    max(truthXY(:,2)) + marginM]);


xlabel('x / m');
ylabel('y / m');

title('OMP recovered four targets');

grid on;

legend( ...
    {'Truth', 'OMP estimate'}, ...
    'Location', ...
    'best');

hold off;


%% ============================================================
% Plot 3: residual convergence
% =============================================================

figure( ...
    'Name', ...
    'Four-target OMP residual convergence', ...
    'Color', ...
    'w');


semilogy( ...
    1:numTargets, ...
    ompResult.residualRelativeErrorHistory, ...
    '-o', ...
    'LineWidth', ...
    1.5);

grid on;

xticks(1:numTargets);

xlabel('OMP iteration');
ylabel('Relative residual error');

title('Four-target OMP residual convergence');


%% ============================================================
% Local function: optimal truth/detection assignment
% =============================================================

function [matchedXY, matchedAlpha, bestAssignment] = ...
    matchDetectionsToTruth( ...
        truthXY, ...
        detectedXY, ...
        detectedAlpha)

numTargets = ...
    size(truthXY,1);


allAssignments = ...
    perms(1:numTargets);


bestCost = ...
    Inf;

bestAssignment = ...
    1:numTargets;


for k = 1:size(allAssignments,1)

    assignment = ...
        allAssignments(k,:);


    candidateXY = ...
        detectedXY(assignment,:);


    errorM = ...
        vecnorm( ...
            candidateXY - ...
            truthXY, ...
            2, ...
            2);


    cost = ...
        sum(errorM);


    if cost < bestCost

        bestCost = ...
            cost;

        bestAssignment = ...
            assignment;

    end

end


matchedXY = ...
    detectedXY(bestAssignment,:);

matchedAlpha = ...
    detectedAlpha(bestAssignment);

end