clear;
close all;
clc;

startup;

%% Configuration

cfg = mmw.config.defaultConfig();

array = mmw.geometry.makeArray( ...
    "golomb", ...
    cfg.array);

carrierHz = (60:0.4:64) * 1e9;

numCarriers = numel(carrierHz);


%% Build two-target scene

sceneTwo = mmw.geometry.makeScene( ...
    "two", ...
    cfg.scene, ...
    0.05);


%% Run original two-target simulation

fprintf('\n========================================\n');
fprintf('TWO-TARGET SCENE\n');
fprintf('========================================\n');

twoResult = mmw.fusion.runCarrierSet( ...
    cfg, ...
    array, ...
    sceneTwo, ...
    carrierHz, ...
    "coherent-normalized");


%% ============================================================
% STEP 1
% Detect the strongest target
% =============================================================

P = twoResult.fusedImage.coherentPower;

[~, linearIndex] = ...
    max(P(:));

[iy1, ix1] = ...
    ind2sub( ...
        size(P), ...
        linearIndex);

x = twoResult.fusedImage.xGridM;
y = twoResult.fusedImage.yGridM;

detectedPosition1M = [ ...
    x(ix1), ...
    y(iy1), ...
    cfg.imaging.zM];


fprintf('\n========================================\n');
fprintf('FIRST TARGET DETECTION\n');
fprintf('========================================\n');

fprintf( ...
    'Target 1 position : (%.4f, %.4f, %.4f) m\n', ...
    detectedPosition1M(1), ...
    detectedPosition1M(2), ...
    detectedPosition1M(3));


%% Build unit template for detected Target 1

targetTemplate1.name = ...
    "Template1";

targetTemplate1.positionM = ...
    detectedPosition1M;

targetTemplate1.velocityMps = ...
    cfg.scene.defaultVelocityMps;

targetTemplate1.rcsM2 = 1.0;

targetTemplate1.scatterPhaseRad = 0.0;

templateScene1.type = "single";
templateScene1.separationM = NaN;
templateScene1.targets = targetTemplate1;


%% ============================================================
% STEP 2
% Ordinary CLEAN coefficient estimation
%
% This intentionally reproduces the previous CLEAN method.
% It is used only to obtain the residual for detecting Target 2.
% =============================================================

templateIF1 = cell(1, numCarriers);

numerator1 = 0;
denominator1 = 0;


for k = 1:numCarriers

    cfgK = cfg;
    cfgK.waveform.fcHz = carrierHz(k);

    [s1, ~] = ...
        mmw.signal.simulateIF( ...
            cfgK, ...
            array, ...
            templateScene1);

    templateIF1{k} = s1;

    yObserved = ...
        twoResult.carrierResults{k}.ifData;

    numerator1 = ...
        numerator1 + ...
        sum(conj(s1(:)) .* yObserved(:));

    denominator1 = ...
        denominator1 + ...
        sum(abs(s1(:)).^2);

end


alphaClean1 = ...
    numerator1 / denominator1;


fprintf('\n========================================\n');
fprintf('ORDINARY CLEAN COEFFICIENT\n');
fprintf('========================================\n');

fprintf( ...
    'Amplitude : %.6f\n', ...
    abs(alphaClean1));

fprintf( ...
    'Phase     : %.3f deg\n', ...
    rad2deg(angle(alphaClean1)));

fprintf( ...
    'Alpha     : %.6f %+.6fj\n', ...
    real(alphaClean1), ...
    imag(alphaClean1));


%% ============================================================
% STEP 3
% Remove Target 1 using ordinary CLEAN
% and detect Target 2 from the residual
% =============================================================

residualComplexStack = [];


for k = 1:numCarriers

    cfgK = cfg;
    cfgK.waveform.fcHz = carrierHz(k);

    yObserved = ...
        twoResult.carrierResults{k}.ifData;

    s1 = ...
        templateIF1{k};

    residualIF = ...
        yObserved - ...
        alphaClean1 * s1;


    residualRD = ...
        mmw.processing.rangeDoppler( ...
            cfgK, ...
            residualIF);


    residualImage = ...
        mmw.imaging.coherentImage( ...
            cfgK, ...
            array, ...
            residualRD);


    if isempty(residualComplexStack)

        [numY, numX] = ...
            size( ...
                residualImage.coherentComplex);

        residualComplexStack = ...
            complex(zeros( ...
                numY, ...
                numX, ...
                numCarriers));

    end


    residualComplexStack(:,:,k) = ...
        residualImage.coherentComplex;

end


%% Fuse CLEAN residual

[residualPower, ...
 residualComplex, ...
 residualNormalizedStack] = ...
    mmw.fusion.fuseComplexImages( ...
        residualComplexStack, ...
        "normalized");


%% Detect Target 2 from residual

[~, residualLinearIndex] = ...
    max(residualPower(:));

[iy2, ix2] = ...
    ind2sub( ...
        size(residualPower), ...
        residualLinearIndex);


detectedPosition2M = [ ...
    x(ix2), ...
    y(iy2), ...
    cfg.imaging.zM];


fprintf('\n========================================\n');
fprintf('SECOND TARGET DETECTION\n');
fprintf('========================================\n');

fprintf( ...
    'Target 2 position : (%.4f, %.4f, %.4f) m\n', ...
    detectedPosition2M(1), ...
    detectedPosition2M(2), ...
    detectedPosition2M(3));


%% Build unit template for Target 2

targetTemplate2.name = ...
    "Template2";

targetTemplate2.positionM = ...
    detectedPosition2M;

targetTemplate2.velocityMps = ...
    cfg.scene.defaultVelocityMps;

targetTemplate2.rcsM2 = 1.0;

targetTemplate2.scatterPhaseRad = 0.0;

templateScene2.type = "single";
templateScene2.separationM = NaN;
templateScene2.targets = targetTemplate2;


%% ============================================================
% STEP 4
% Joint least-squares estimation
%
% y = alpha1*s1 + alpha2*s2
%
% Instead of estimating the two targets independently,
% solve both coefficients simultaneously.
% =============================================================

G = complex(zeros(2,2));
b = complex(zeros(2,1));

templateIF2 = cell(1, numCarriers);


for k = 1:numCarriers

    cfgK = cfg;
    cfgK.waveform.fcHz = carrierHz(k);

    s1 = ...
        templateIF1{k};


    [s2, ~] = ...
        mmw.signal.simulateIF( ...
            cfgK, ...
            array, ...
            templateScene2);

    templateIF2{k} = s2;


    yObserved = ...
        twoResult.carrierResults{k}.ifData;


    %% Two-column forward model for this carrier

    Sk = [ ...
        s1(:), ...
        s2(:)];


    %% Accumulate normal equations
    %
    % G = S^H S
    % b = S^H y

    G = ...
        G + ...
        Sk' * Sk;

    b = ...
        b + ...
        Sk' * yObserved(:);

end


%% Joint LS solution
%
% Do NOT explicitly compute inv(G).

alphaJoint = ...
    G \ b;


alpha1Joint = ...
    alphaJoint(1);

alpha2Joint = ...
    alphaJoint(2);


%% Template coherence

templateCoherence = ...
    abs(G(1,2)) / ...
    sqrt( ...
        real(G(1,1)) * ...
        real(G(2,2)));


gramConditionNumber = ...
    cond(G);


fprintf('\n========================================\n');
fprintf('JOINT LS RESULT\n');
fprintf('========================================\n');

fprintf('\nTarget 1:\n');

fprintf( ...
    '  amplitude = %.9f\n', ...
    abs(alpha1Joint));

fprintf( ...
    '  phase     = %.6f deg\n', ...
    rad2deg(angle(alpha1Joint)));

fprintf( ...
    '  alpha     = %.9f %+.9fj\n', ...
    real(alpha1Joint), ...
    imag(alpha1Joint));


fprintf('\nTarget 2:\n');

fprintf( ...
    '  amplitude = %.9f\n', ...
    abs(alpha2Joint));

fprintf( ...
    '  phase     = %.6f deg\n', ...
    rad2deg(angle(alpha2Joint)));

fprintf( ...
    '  alpha     = %.9f %+.9fj\n', ...
    real(alpha2Joint), ...
    imag(alpha2Joint));


fprintf('\nTemplate coherence = %.6f\n', ...
    templateCoherence);

fprintf( ...
    'Gram condition number = %.6f\n', ...
    gramConditionNumber);


%% ============================================================
% STEP 5
% Reconstruct the complete two-target observation
% and examine the residual
% =============================================================

residualEnergy = 0;
observedEnergy = 0;


for k = 1:numCarriers

    yObserved = ...
        twoResult.carrierResults{k}.ifData;

    s1 = ...
        templateIF1{k};

    s2 = ...
        templateIF2{k};


    yReconstructed = ...
        alpha1Joint * s1 + ...
        alpha2Joint * s2;


    reconstructionResidual = ...
        yObserved - ...
        yReconstructed;


    residualEnergy = ...
        residualEnergy + ...
        sum(abs(reconstructionResidual(:)).^2);

    observedEnergy = ...
        observedEnergy + ...
        sum(abs(yObserved(:)).^2);

end


jointResidualRelativeError = ...
    sqrt( ...
        residualEnergy / ...
        max(observedEnergy, eps));


fprintf('\n========================================\n');
fprintf('JOINT RECONSTRUCTION CHECK\n');
fprintf('========================================\n');

fprintf( ...
    'Relative residual error = %.3e\n', ...
    jointResidualRelativeError);


%% ============================================================
% STEP 6
% Use the corrected joint alpha1 to remove Target 1 again.
%
% If joint LS works, what remains should now be almost exactly
% Target 2 instead of the 17 %% error of ordinary CLEAN.
% =============================================================

jointTarget2ComplexStack = [];


for k = 1:numCarriers

    cfgK = cfg;
    cfgK.waveform.fcHz = carrierHz(k);

    yObserved = ...
        twoResult.carrierResults{k}.ifData;

    s1 = ...
        templateIF1{k};


    %% Remove Target 1 using JOINT coefficient

    target2IF = ...
        yObserved - ...
        alpha1Joint * s1;


    target2RD = ...
        mmw.processing.rangeDoppler( ...
            cfgK, ...
            target2IF);


    target2Image = ...
        mmw.imaging.coherentImage( ...
            cfgK, ...
            array, ...
            target2RD);


    if isempty(jointTarget2ComplexStack)

        [numY, numX] = ...
            size( ...
                target2Image.coherentComplex);

        jointTarget2ComplexStack = ...
            complex(zeros( ...
                numY, ...
                numX, ...
                numCarriers));

    end


    jointTarget2ComplexStack(:,:,k) = ...
        target2Image.coherentComplex;

end


%% Fuse isolated Target 2

[jointTarget2Power, ...
 jointTarget2Complex, ...
 jointTarget2NormalizedStack] = ...
    mmw.fusion.fuseComplexImages( ...
        jointTarget2ComplexStack, ...
        "normalized");


%% Build image structure

jointTarget2Image = ...
    twoResult.carrierResults{1}.image;

jointTarget2Image.coherentComplex = ...
    jointTarget2Complex;

jointTarget2Image.coherentPower = ...
    jointTarget2Power;

jointTarget2Image.nodeComplex = [];
jointTarget2Image.nodePower = [];
jointTarget2Image.noncoherentPower = [];

jointTarget2Image.method = ...
    "joint-LS Target 2 isolation";


%% ============================================================
% STEP 7
% Truth is used from here ONLY for evaluation
% =============================================================

scene2Truth = sceneTwo;
scene2Truth.type = "single";
scene2Truth.targets = sceneTwo.targets(2);


target2Reference = ...
    mmw.fusion.runCarrierSet( ...
        cfg, ...
        array, ...
        scene2Truth, ...
        carrierHz, ...
        "coherent-normalized");


%% Evaluate isolated target

jointMetrics = ...
    mmw.metrics.evaluateImage( ...
        cfg, ...
        scene2Truth, ...
        jointTarget2Image);


referenceMetrics = ...
    target2Reference.metrics;


%% Image error

jointImageError = ...
    norm( ...
        jointTarget2Complex(:) - ...
        target2Reference.fusedImage.coherentComplex(:)) / ...
    max( ...
        norm( ...
            target2Reference.fusedImage.coherentComplex(:)), ...
        eps);


fprintf('\n========================================\n');
fprintf('JOINT LS TARGET-2 ISOLATION\n');
fprintf('========================================\n');

fprintf( ...
    'Localization error : %.3f mm\n', ...
    1000 * jointMetrics.localizationErrorM);

fprintf( ...
    'PSLR               : %.3f dB\n', ...
    jointMetrics.pslrDb);

fprintf( ...
    'ISLR               : %.3f dB\n', ...
    jointMetrics.islrDb);

fprintf( ...
    'Image error        : %.3e\n', ...
    jointImageError);


fprintf('\nReference:\n');

fprintf( ...
    'Localization error : %.3f mm\n', ...
    1000 * referenceMetrics.localizationErrorM);

fprintf( ...
    'PSLR               : %.3f dB\n', ...
    referenceMetrics.pslrDb);

fprintf( ...
    'ISLR               : %.3f dB\n', ...
    referenceMetrics.islrDb);


%% ============================================================
% STEP 8
% Plot
% =============================================================

Poriginal = ...
    twoResult.fusedImage.coherentPower;

Pjoint = ...
    jointTarget2Image.coherentPower;

Preference = ...
    target2Reference.fusedImage.coherentPower;


Poriginal = ...
    Poriginal / max(Poriginal(:));

Pjoint = ...
    Pjoint / max(Pjoint(:));

Preference = ...
    Preference / max(Preference(:));


dynamicRangeDb = ...
    cfg.plot.dynamicRangeDb;


figure( ...
    'Name', ...
    'Joint LS validation', ...
    'Position', ...
    [100 150 1500 500]);


tiledlayout( ...
    1, ...
    3, ...
    'TileSpacing', ...
    'compact', ...
    'Padding', ...
    'compact');


%% Original image

nexttile;

imagesc( ...
    x, ...
    y, ...
    10*log10(Poriginal + eps));

axis xy equal tight;
clim([-dynamicRangeDb 0]);

xlabel('x / m');
ylabel('y / m');

title('Original two-target image');


%% Joint-LS isolation

nexttile;

imagesc( ...
    x, ...
    y, ...
    10*log10(Pjoint + eps));

axis xy equal tight;
clim([-dynamicRangeDb 0]);

xlabel('x / m');
ylabel('y / m');

title('Joint-LS isolated Target 2');


%% Reference

nexttile;

imagesc( ...
    x, ...
    y, ...
    10*log10(Preference + eps));

axis xy equal tight;
clim([-dynamicRangeDb 0]);

xlabel('x / m');
ylabel('y / m');

title('Target 2 only');

colorbar;


%% Difference image

figure( ...
    'Name', ...
    'Joint LS image difference');

imagesc( ...
    x, ...
    y, ...
    abs(Pjoint - Preference));

axis xy equal tight;

xlabel('x / m');
ylabel('y / m');

title( ...
    'Absolute power difference: joint LS vs Target 2');

colorbar;


%% ============================================================
% FINAL SUMMARY
% =============================================================

fprintf('\n========================================\n');
fprintf('FINAL SUMMARY\n');
fprintf('========================================\n');

fprintf( ...
    'Detected Target 1 : (%.4f, %.4f) m\n', ...
    detectedPosition1M(1), ...
    detectedPosition1M(2));

fprintf( ...
    'Detected Target 2 : (%.4f, %.4f) m\n', ...
    detectedPosition2M(1), ...
    detectedPosition2M(2));

fprintf('\nOrdinary CLEAN alpha1:\n');

fprintf( ...
    '  |alpha1| = %.6f\n', ...
    abs(alphaClean1));

fprintf( ...
    '  phase    = %.3f deg\n', ...
    rad2deg(angle(alphaClean1)));


fprintf('\nJoint LS:\n');

fprintf( ...
    '  |alpha1| = %.9f\n', ...
    abs(alpha1Joint));

fprintf( ...
    '  phase1   = %.6f deg\n', ...
    rad2deg(angle(alpha1Joint)));

fprintf( ...
    '  |alpha2| = %.9f\n', ...
    abs(alpha2Joint));

fprintf( ...
    '  phase2   = %.6f deg\n', ...
    rad2deg(angle(alpha2Joint)));

fprintf( ...
    '  coherence = %.6f\n', ...
    templateCoherence);

fprintf( ...
    '  cond(G)   = %.6f\n', ...
    gramConditionNumber);

fprintf( ...
    '  residual  = %.3e\n', ...
    jointResidualRelativeError);

fprintf( ...
    '  image err = %.3e\n', ...
    jointImageError);