function test_omp_two_target()
%TEST_OMP_TWO_TARGET Regression test for two-target OMP recovery.

cfg = ...
    mmw.config.defaultConfig();

exp = ...
    mmw.config.defaultExperiment();


exp.sceneSpec = ...
    "two";

exp.separationM = ...
    0.05;

exp.reconstruction.maxTargets = ...
    2;


result = ...
    mmw.runExperiment( ...
        exp, ...
        cfg);


m = ...
    result.ompMetrics;


assert( ...
    m.supportPass, ...
    'Two-target support recovery failed.');


assert( ...
    m.maxPositionErrorM <= 1e-9, ...
    'Two-target on-grid localization changed.');


assert( ...
    max(m.alphaAmplitudeError) <= 1e-10, ...
    'Two-target amplitude recovery changed.');


assert( ...
    max(m.alphaPhaseErrorDeg) <= 1e-8, ...
    'Two-target phase recovery changed.');


assert( ...
    m.finalResidualRelativeError <= 1e-10, ...
    'Two-target OMP residual became too large.');


fprintf( ...
    'test_omp_two_target passed.\n');

end